### ISSUE TITLE
Incorrect position of top elements

### ISSUE THREAD

**Issue by swandevv** [dubaua/immerser#1]
It works properly if section height equal to or more than 100vh. Otherwise, the position of the top element doesn't match the section top edge.

**Comment by dubaua** [comment]
@swandevv Hi. Could you provide a jsfiddle representing the problem please? I turned off `min-height: 100vh;` on my `tall` classname and reinit immerser then. And all calculations are fine and the edges of the layers renders correct.

**Comment by swandevv** [comment]
@dubaua 
Look at section 3
https://codepen.io/anon/pen/XwOBbZ

**Comment by dubaua** [comment]
fix that returning bunch of ifs from #6a7cf2e

**Comment by dubaua** [comment]
@swandevv Please, take into account, the library isn't released yet, so it is not supposed to be used in production.
