### ISSUE TITLE
pager

### ISSUE THREAD

**Issue by woobla** [dubaua/immerser#12]
Нет возможности кастомизировать pager если ссылки находятся в потомке самого pager.

**Пример:**
```
<div class="w-grid__alp sidebar" data-immerser-pager data-immerser-solid="pager">
    <div class="w-grid__alp-cnt _p-header _p-cnt sidebar__wrap">
      <div class="sidebar__menu">
        <a class="sidebar__item pager__link" data-immerser-synchro-hover="sidebar-item-a" href="#sect-1">Секция 1</a>
        <a class="sidebar__item pager__link" data-immerser-synchro-hover="sidebar-item-a-1" href="#sect-2">Секция 2</a>
      </div>
    </div>
  </div>
```
Скирпт создает ссылки непосредственно в блоке pager

Если ссылка pager__link будет содержать в себе потомков, то не сработает synchro-hover.
```<a class="pager__link" data-immerser-synchro-hover="sidebar-item-a-1" href="#sect-2"><span>Потомок</span></a>```

Даже если передать евент mouseover при наведении на потомка в родительский pager__link.

**Comment by woobla** [comment]
Если в data-immerser-layer-config='{"pager": "_sidebar-default"}' передать пустое значение data-immerser-layer-config='{"pager": ""}' то скрипт упадет с ошибкой, хотя логично чтобы было удаление классов добавленных иммерсером.

**Comment by woobla** [comment]
Без pager не дает использовать иммерсер.

**Comment by dubaua** [comment]
Эта проблема известна и решена в ветке, но еще не подлита, так как есть небольшие проблемы с конфигом вебпака.

**Comment by woobla** [comment]
Можно кстати добавить еще параметр типа data-immerser-pager-title для layer чтобы генерировать pager__link с текстом

Я сделал у себя так:
```
      [...document.querySelectorAll('[data-immerser-pager-title]')].forEach(el => {
        let sectId = el.getAttribute('id');
        let sectTitle = el.getAttribute('data-immerser-pager-title');
        if (sectId && sectTitle) {
          [...document.querySelectorAll(`.sidebar__item[href="#${sectId}"]`)].forEach(link => {
            link.innerHTML = sectTitle;
          });
        }
      });
```
