### ISSUE TITLE
Listen for document resize?

### ISSUE THREAD

**Issue by Cevorob** [dubaua/immerser#32]
Hi, Im very happy with how immerser works, but I use it on a website with a lot of animations etc. and I cant make it without some javascript that affects document height (dropdowns, sliders,...). I saw a handleResize() function used on window resize, so I added ResizeObserver for the whole document and used the handleResize function in each entry. This solution works as I wanted, wouldnt it be a good idea to implement this in Immerser? Or mention it somewhere as a possible solution?

**Comment by dubaua** [comment]
Hello, thank you for feedback.

I assume ResizeObserver callback is firing after actual height of the document is changes, so you do not need schedule setting sizes and draw immerser. And you can call setSizes and draw methods in your callback.

I think I will add your approach in the documentation, but first I need to design and add a section for recipes ;)

**Comment by Cevorob** [comment]
I dont understant 100% what you said, but yes, the problem is with actual document height changes. My question can be simplified: why not add to this `window.addEventListener('resize', this.onResize, false);` some solution that listenes to actual document height changes?
Because when document height changes, immerser will always break. It needs to be recalculated... From my point of view its a no-brainer to add this feature :)

**Comment by dubaua** [comment]
We already have this here https://github.com/dubaua/immerser/blob/master/src/immerser.js#L237

Your problem is you change document height manually, and resize event isn't fired this case. Because resize event fired when you resize browser window. Instead of listen to window resize, you should manually call setSizes and draw methods on immerser instance after height is changed. You can do it after DOM manipulation.

**Comment by Cevorob** [comment]
Yes, thats what Im talking about. Shouldnt that be implemented from default?

**Comment by dubaua** [comment]
How can library know when DOM is manually changed?

**Comment by Cevorob** [comment]
Good question :D I got carried away with my specific case. I think it would be best to add this solution into recipes section as you said :)
