### ISSUE TITLE
Cannot get Immerser to work

### ISSUE THREAD

**Issue by JonQuayle** [dubaua/immerser#4]
Hi,

I am having difficulty getting this to work at all. Have followed the explanation but keep getting the error message can't find variable immerser in the console. I've stripped everything back so I am just trying to try it on one element but still no luck... any tips on getting this to work?

**Comment by dubaua** [comment]
Hello. 

How do you use immerser? I suppose you're using umd build? 

Can you provide example of your code?

**Comment by JonQuayle** [comment]
I'm using the umd build yes.

I started by using a very basic implementation:

`<div class="header" data-immerser>
        <div class="parent flex justify-between items-center">
            <p class="logo" data-immerser-solid="logo">logo</p>
            <nav class="navbar">
                <div id="toggle" class="btn--animated-background-y menu-toggle">
                    <div><span class="btn--animated-background-ySpan">Menu</span></div>
                </div>
            </nav>
        </div>
    </div>`

and then this section further down the page:

`<section id="featuredHome" class="featured-home" data-scroll-section data-immerser-layer
  data-immerser-layer-config='{"logo": "logo--contrast"}'></section>`

Then, adding in the JS according to the readme, but from what I can see, taking the options out as they are being defined in the code above?

`import Immerser from 'immerser';

const immerserInstance = new Immerser({
});`

The only thing I can think of that could be causing it to not work is that I am also using the Locomotive Scroll library (https://github.com/locomotivemtl/locomotive-scroll#instance-events). Could there be some incompatibility there? I might be doing this wrong - not the strongest as javascript. Thanks

**Comment by dubaua** [comment]
I see here two potential problems:

1. You have only one layer, so even if immerser will work you can see it, because it can't change color because it happen when scrolling between layers.

2. It looks like I've not tested immerser without pager and there was an error on binding the library.

For now I recommend you not use immerser as umd, because there is a problem with bundler, or wait for fixing it. It would take day or two.

**Comment by dubaua** [comment]
Please fetch [a new umd build](https://unpkg.com/immerser@2.0.3/dist/immerser.min.umd.js) now this should work. Also I've updated documentation and remark confusing import as unnecessary if using UMD
