### ISSUE TITLE
Working with 'position:sticky' instead of 'position:fixed'

### ISSUE THREAD

**Issue by cangoktas** [dubaua/immerser#40]
Hey there, is there a way to use immerser with `position:sticky` instead of `position:fixed`? As far as I understand, immerser needs a fixed holder for the element that will change on scroll. Hovewer my container (`<header>`) should be sticky. I plan to use the library for swapping my SVG logo's color depending on some sections (switching from light logo to dark, either via changing svg path colors with CSS or showing/hiding `<img>` using classes). By default, `position:fixed` elements are aligned to the viewport and can't be aligned to the container element whatsoever, so I'm kind of desperate in this situation. Any ideas?

Working example with `position:fixed`: [Codepen](https://codepen.io/cangoktas/pen/MWOvaPK)
Desired & not working example w/ `position:sticky` container: [Codepen](https://codepen.io/cangoktas/pen/qBVXOyX)

**Comment by dubaua** [comment]
Hello. With the current version of the library, it seems not possible, because the library listens to window scroll and calculates all values from the screen. But I'm working on the new version, where a user can make any scrollable root as the immerser root and archive a sticky position to work.

I'm sorry for the late reply, I was ill.

**Comment by cangoktas** [comment]
Hey Vladimir! Thanks for the answer & hope you feel much better now :)
Regarding the new version, I can also give feedback about the documentation too: It could be awesome if you'd explain different use cases with demos too. As a designer who codes I had a bit of struggle to understand what kind of DOM architecture should I build and which attributes mean what. For example, I was able to achieve simply masking a text light/dark depending on background, but I couldn't figure out how to switch <img> or <svg>'s instead of simple text even though you had an svg emoji on the landing page. Or what the "pager" empty div does and do I need it. 

Still, Immerser is the only modern and working library of its kind and thank your the great work you've done 💪
